name: 'Set up Theos'
description: 'Set up Theos for building projects in workflows'
author: 'Nebula'
inputs:
  theos-dir:
    description: 'Where to install Theos'
    required: false
    default: theos
  theos-src:
    description: 'Where to clone Theos itself from (git URL)'
    required: false
    default: 'https://github.com/theos/theos'
  theos-branch:
    description: 'Branch of Theos to clone'
    required: false
    default: 'master'
  theos-sdks:
    description: 'Where to clone the iOS SDKs from (github repo without github.com)'
    required: false
    default: 'itsnebulalol/sdks'
  procursus-mirror:
    description: 'Mirror of Procursus to use (on macOS)'
    required: false
    default: 'https://procursus.itsnebula.net/'
runs:
  using: "composite"
  steps:
    - name: Set up Procursus
      uses: itsnebulalol/procursus-action@patch-2
      if: runner.os == 'macOS'
      with:
        packages: ldid make
        cache: true
        cache-path: ~/__cache
        mirror: '${{ inputs.procursus-mirror }}'
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get install build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git zstd -y
        
        curl -L https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64 -o ldid
        chmod +x ldid
        sudo mv ldid /usr/bin/ldid
        
    - name: Prepare environment
      shell: bash
      run: |
        echo "THEOS=${{ github.workspace }}/${{ inputs.theos-dir }}" >> $GITHUB_ENV

    - name: Get Theos
      shell: bash
      run: |
        rm -rf ${{ github.workspace }}/${{ inputs.theos-dir }}
        git clone --recursive ${{ inputs.theos-src }} ${{ github.workspace }}/${{ inputs.theos-dir }} -b ${{ inputs.theos-branch }}
        cd ${{ github.workspace }}/${{ inputs.theos-dir }}

        curl -L https://api.github.com/repos/${{ inputs.theos-sdks }}/tarball -o sdks.tar.gz
        TMP=$(mktemp -d)
        tar -xvf sdks.tar.gz --strip=1 -C $TMP
        mv $TMP/*.sdk ${{ github.workspace }}/${{ inputs.theos-dir }}/sdks
        rm -r sdks.tar.gz $TMP
        
        if [ "$RUNNER_OS" == "Linux" ]; then
            curl -LO https://github.com/CRKatri/llvm-project/releases/download/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.zst
            TMP=$(mktemp -d)
            tar -xvf swift-5.3.2-RELEASE-ubuntu20.04.tar.zst -C $TMP
            mkdir -p ${{ github.workspace }}/${{ inputs.theos-dir }}/toolchain/linux/iphone ${{ github.workspace }}/${{ inputs.theos-dir }}/toolchain/swift
            mv $TMP/swift-5.3.2-RELEASE-ubuntu20.04/* ${{ github.workspace }}/${{ inputs.theos-dir }}/toolchain/linux/iphone/
            ln -s ${{ github.workspace }}/${{ inputs.theos-dir }}/toolchain/linux/iphone ${{ github.workspace }}/${{ inputs.theos-dir }}/toolchain/swift
            rm -r swift-5.3.2-RELEASE-ubuntu20.04.tar.zst $TMP
        fi

        cd ${{ github.workspace }}
        ${{ github.workspace }}/${{ inputs.theos-dir }}/bin/update-theos

branding:
  icon: download-cloud
  color: purple
