name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v3
        with:
          repository: itsnebulalol/testtweak
          
      - name: Run Theos action
        uses: itsnebulalol/theos-action@main
      
      - name: Build tweak
        run: make clean package FINALPACKAGE=1
          
      - name: Upload tweak
        uses: actions/upload-artifact@v3
        with:
          name: tweak-${{ matrix.os }}
          path: ${{ github.workspace }}/packages/*
